class SightingsController < ApplicationController
  def index
    sightings = Sighting.all 
    render json: SightingSerializer.new(sightings)
  end

  def show
    sighting = Sighting.find_by(id: params[:id])
    options = {
      include: [:bird, :location]
    }
    render json: SightingSerializer.new(sighting, options)

    # render json: sighting.to_json(:include => 
    #   {
    #     :bird => {:only =>[:name, :species]}, 
    #     :location => {:only =>[:latitude, :longitude]}}, 
    #     :except => [:updated_at])
  end
end

# Serializers generated by the FAST JSON API gem have two build-in methods: 
# serializable_hash   => This returns a serialized hash 
# serialized_json => This returns a JSON string
# We don't need either in this example because to_json will be implicitly called on SightingSerializer.new(sighting)
